from django.urls import path
from stephan import views
import django.contrib.auth.views as auth_views
from .views import (TenantUpdateView,
                    TenantDetailView,
                    BedspaceCreateView,
                    BedroomCreateView,
                    BedroomDetailView,
                    BedroomUpdateView,
                    BedroomDeleteView,
                    TenantDeleteView,
                    BedspaceDetailView,
                    BedspaceUpdateView,
                    BedspaceDeleteView,
                    SettingsView,
                    ReceiptDetailView,)

urlpatterns = [
    path('', views.welcome, name='sophans'),
    path('tenant_signup/',views.signup, name="tenant-signup"),
    path('home/', views.home, name="dashboard"),
    path('terms/', views.term_privacy, name="terms"),
    path('profile-update/', views.profileUpdate, name='profile-update'),
    path('profile/', views.profileview, name='profile'),
    path('rooms/', views.roomList, name="rooms"),
    path('bedspaces/', views.bedspaceList, name="bedspaces"),
    path('tenants/', views.tenantList, name="tenants"),
    path('tenant-create/', views.tenantcreate, name="tenant-create"),
    path('tenant-update/<int:pk>/', TenantUpdateView.as_view(template_name='stephan/tenant_update_form.html'), name="tenant-update"),
    path('tenant-detail/<int:pk>/', TenantDetailView.as_view(), name="tenant-detail"),
    path('tenant-delete/<int:pk>/', TenantDeleteView.as_view(), name="tenant-delete"),
    path('room-create/', BedroomCreateView.as_view(), name="room-create"),
    path('bedspace-create/', BedspaceCreateView.as_view(), name="bedspace-create"),
    path('bedspace-detail/<int:pk>/', BedspaceDetailView.as_view(), name="bedspace-detail"),
    path('bedspace-update/<int:pk>/', BedspaceUpdateView.as_view(), name="bedspace-update"),
    path('bedspace-delete/<int:pk>/', BedspaceDeleteView.as_view(), name="bedspace-delete"),
    path('room-detail/<int:pk>/', BedroomDetailView.as_view(), name="bedroom-detail"),
    path('room-update/<int:pk>/', BedroomUpdateView.as_view(), name="bedroom-update"),
    path('room-delete/<int:pk>/', BedroomDeleteView.as_view(), name="bedroom-delete"),
    path('transactions/', views.transactionsList, name="transactions"),
    path('settings/', SettingsView.as_view(), name="settings"),
    path('email_change/', views.change_email, name="email-change"),
    path('delete_data/', views.deleteAccount, name="delete-account"),
    path('delete_user_date/', views.deleteUserData, name="delete-user-data"),
    path('about_us/', views.aboutMnsft, name="about-us"),
    path("submit-feedback/", views.submit_feedback, name="submit_feedback"),
    #path('tenant_pdf/', views.tenant_pdf, name='tenant-pdf'),
    #path('transaction_pdf/', views.transactions_pdf, name='transaction-pdf'),
    #path('tenant_excel/', views.tenant_excel, name='tenant-excel'),
    #path('transaction_excel/', views.transactions_excel, name='transaction-excel'),
    path('msg/', views.msg, name='msg'),
    path('receipt/', views.receipt, name='receipt'),
    path('my_receipts/', views.my_receipts, name='my_receipts'),
    #path('receipts_pdf/', views.receipts_pdf, name='receipts-pdf'),
    path('receipts_detail/<int:pk>/', ReceiptDetailView.as_view(), name="receipt-detail"),
]